service: monitoring-frontend-app

plugins:
  - serverless-single-page-app-plugin
  - serverless-plugin-tracing
  - serverless-appsync-plugin
  - '@anttiviljami/serverless-stack-output'

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(../services/common/environment/config.${self:custom.currentStage}.json):region}

  output:
    handler: ../scripts/stackOutput.handler

  s3Bucket: monitoring-frontend-app-bucket-${self:custom.currentStage}

  appSync:
    name: monitoring-data-endpoint
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:custom.currentRegion}
      defaultAction: ALLOW
      userPoolId: { Ref: UserPool }
    serviceRole: AppSyncServiceRole
    dataSources:
      - type: AMAZON_DYNAMODB
        name: DataEntries
        description: 'Monitoring Data Entries Source'
        config:
          tableName:
            Fn::ImportValue: 'monitoring-service:${self:custom.currentStage}:MonitoringDataTableName'
          serviceRoleArn:
            Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - ':role/Dynamo-${self:custom.appSync.serviceRole}'

    mappingTemplatesLocation: ./appsync/mapping-templates
    schema: ./appsync/schema.graphql
    mappingTemplates:
      - dataSource: DataEntries
        type: Query
        field: getDataEntries
        request: 'data-entry-request-mapping-template.txt'
        response: 'data-entry-response-mapping-template.txt'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}

  logRetentionInDays: 7

  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: 'Allow' # xray permissions (required)
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

resources:
  # cloudfront
  - ${file(resources/cloudfront.yml)}

  # appsync service role
  - ${file(resources/appsync-service-role.yml)}

  # cognito
  - ${file(resources/cognito.yml)}
