version: 0.2

env:
  parameter-store:
    region_staging: 'region-staging'
    region_prod: 'region-prod'
    adminEmail_staging: 'adminEmail-staging'
    adminEmail_prod: 'adminEmail-prod'

phases:
  install:
    commands:
      - echo performing install phase
      # Setup for Serverless
      - npm install -g serverless
      # Setup for Yarn
      - sudo apt-get update -y && sudo apt-get install -y make apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update -y && sudo apt-get install -y yarn
  pre_build:
    commands:
      - echo performing pre_build phase
      - yarn install
      - echo configuring environment variables
      - cp -f services/common/environment/config.example.json services/common/environment/config.${STAGE}.json
      - sed -i 's/REGION_VALUE/${region_${STAGE}}/g' services/common/environment/config.${STAGE}.json
      - sed -i 's/ADMIN_EMAIL_VALUE/${adminEmail_${STAGE}}/g' services/common/environment/config.${STAGE}.json
  build:
    commands:
      - echo performing build phase
      - yarn lint
      - yarn test
      - yarn run:all:${STAGE}
  post_build:
    commands:
      - echo performing post_build phase
      - yarn test:e2e
