service: cicd
plugins:
  - serverless-plugin-cicd

custom:
  defaultStage: staging
  currentStage: ${opt:stage, self:custom.defaultStage}
  config: ${file(./config.js)}

  cicd:
    image: 'aws/codebuild/nodejs:8.11.0'
    owner: ${self:custom.config.githubOwner}
    repository: ${self:custom.config.githubRepo}
    githubtoken: '{{resolve:ssm:githubToken:1}}'

  staging:
    branch: staging
  prod:
    branch: prod

provider:
  name: aws
  stage: ${self:custom.currentStage}
  region: ${self:custom.config.region}
