service: cicd
plugins:
  - serverless-plugin-cicd

custom:
  defaultStage: staging
  currentStage: ${opt:stage, self:custom.defaultStage}
  github: ${file(./scripts/githubConfig.js)}
  regions: ${file(./package.json):regions}

  cicd:
    image: 'aws/codebuild/nodejs:8.11.0'
    owner: ${self:custom.github.owner}
    repository: ${self:custom.github.repo}

    staging:
      # build on pull requests where master is the base branch
      buildOnPullRequest: master
      # build on push events to master
      buildOnPush: master
    prod:
      # build on tags starting with 'v'
      buildOnTag: 'v.*'

provider:
  name: aws
  stage: ${self:custom.currentStage}
  region: ${self:custom.regions.${self:custom.currentStage}}
