service: cicd
plugins:
  - serverless-plugin-cicd
  - serverless-s3-remover

custom:
  defaultStage: staging
  currentStage: ${opt:stage, self:custom.defaultStage}
  github: ${file(./githubConfig.js)}
  s3ArtifactBucket: ${self:service}-artifact-store-${self:custom.currentStage}
  regions: ${file(./package.json):regions}

  cicd:
    image: 'aws/codebuild/nodejs:8.11.0'
    owner: ${self:custom.github.owner}
    repository: ${self:custom.github.repo}
    githubtoken: '{{resolve:ssm:github-token:1}}'
    artifactStoreBucket: ${self:custom.s3ArtifactBucket}

  remover:
    buckets:
      - ${self:custom.s3ArtifactBucket}

  staging:
    branch: master
    region: eu-west-1
  prod:
    branch: prod
    region: eu-central-1

provider:
  name: aws
  stage: ${self:custom.currentStage}
  region: ${self:custom.regions.${self:custom.currentStage}}
