Resources:
  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      IdentitySource: 'method.request.header.Authorization'
      Name: ${self:service}-${self:custom.currentStage}-cognito-authorizer
      ProviderARNs:
        - Fn::ImportValue: '${self:custom.monitoringCommonServiceName}:${self:custom.currentStage}:UserPoolArn'
      RestApiId: { Ref: ApiGatewayRestApi }
      Type: COGNITO_USER_POOLS
