Resources:
  EndpointsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      TableName: ${self:custom.endpointsTableName}

Outputs:
  EndpointsTableName:
    Value:
      Ref: EndpointsTable
    Export:
      Name: '${self:service}:${self:custom.currentStage}:EndpointsTableName'
