Resources:
  MonitoringDataTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      TableName: ${self:custom.dataTableName}

Outputs:
  MonitoringDataTableName:
    Value:
      Ref: MonitoringDataTable
    Export:
      Name: '${self:service}:${self:custom.currentStage}:MonitoringDataTableName'

  MonitoringDataTableArn:
    Value:
      'Fn::GetAtt': [MonitoringDataTable, Arn]
    Export:
      Name: '${self:service}:${self:custom.currentStage}:MonitoringDataTableArn'
