Resources:
  # An app client for the Amazon Cognito user pool
  UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Description: 'App Client used by AWS AppSync'
    Properties:
      ClientName: ${self:service}-${self:custom.currentStage}-appsync-client
      GenerateSecret: false
      UserPoolId:
        Fn::ImportValue: '${self:custom.monitoringServiceName}:${self:custom.currentStage}:UserPoolId'

Outputs:
  UserPoolClientId:
    Value:
      Ref: UserPoolClient
