Resources:
  AppSyncServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: ${self:custom.serviceRole}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: ${self:custom.serviceRolePolicy}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'dynamodb:Query'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Scan'
                Resource:
                  - Fn::ImportValue: '${self:custom.monitoringCommonServiceName}:${self:custom.currentStage}:MonitoringDataTableArn'
                  - Fn::Join:
                      - ''
                      - - 'Fn::ImportValue': '${self:custom.monitoringCommonServiceName}:${self:custom.currentStage}:MonitoringDataTableArn'
                        - '/*'
